### ISSUE TITLE
rename db group

### ISSUE THREAD

**Issue by devalias** [yahoo/mysql_perf_analyzer#14]
hi, how to rename a db group?

**Comment by xrao** [comment]
We don't provide such feature. Usually I will just create another one. If it is desired, I will think to add it as a future feature.

**Comment by devalias** [comment]
hi, yes it would be a nice feature.  I have servers in a group but I need to rename the group.

**Comment by xrao** [comment]
Please refresh the source, rebuild and test it. Use "DB Info" page, tab "Remove/Rename". Since this project does not create a table to hold db group, it is actually a literal string used by several meta data tables. However, I din't modify ALERTS table, so you will most likely lose some historical alert records.

**Comment by devalias** [comment]
Hi Xrao, I rebuilt but the servers I added disappeared, the groups are still there.
-Michael 


     On Tuesday, June 30, 2015 7:06 PM, xrao <notifications@github.com> wrote:
   

 Please refresh the source, rebuild and test it. Use "DB Info" page, tab "Remove/Rename". Since this project does not create a table to hold db group, it is actually a literal string used by several meta data tables. However, I din't modify ALERTS table, so you will most likely lose some historical alert records. —

**Comment by xrao** [comment]
Please check the log to see if any exception. Also you can try to restart the analyzer. By the way, what do you use for metric store? Java derby or mysql?

**Comment by devalias** [comment]
mysql 


     On Wednesday, July 1, 2015 10:33 AM, xrao <notifications@github.com> wrote:
   

 Please check the log to see if any exception. Also you can try to restart the analyzer. By the way, what do you use for metric store? Java derby or mysql?—

**Comment by xrao** [comment]
I just patched my prod analyzer with my dev build and it worked as expected. Also I just pulled source code from github and did a rebuild and test on a dev instance and it worked without issue. Make sure you did use "Rename a DB Group" option, not "Remove a DB Group" option (yes, the name can be easily messed). 

Since you use mysql server as back store, you can just log into mysql server and check the following tables to see if your servers are still there and DBGROUP column or DBGROUPNAME column was updated:
DBINFOS
ALERTSETTINGS
ALERT_SUBSCRIPT
METRICS_SUBSCRIPT

The rename procedure only tries to update the column DBGROUP or DBGROUPNAME. Only remove option will delete servers.

On the other hand, it will remove saved encrypted  DB credential from a java derby db with the old db group name, and reinsert back with new dbgroup name.

If you can afford another test, can you check the log and paste the log (under directory log)?

**Comment by devalias** [comment]
Hi, I redid the upgrade and it worked just fine, I tried the rename and that works perfectly.  Thanks for adding that feature.
-Michael 


     On Wednesday, July 1, 2015 11:20 AM, xrao <notifications@github.com> wrote:
   

 I just patched my prod analyzer with my dev build and it worked as expected. Also I just pulled source code from github and did a rebuild and test on a dev instance and it worked without issue. Make sure you did use "Rename a DB Group" option, not "Remove a DB Group" option (yes, the name can be easily messed). Since you use mysql server as back store, you can just log into mysql server and check the following tables to see if your servers are still there and DBGROUP column or DBGROUPNAME column was updated:
DBINFOS
ALERTSETTINGS
ALERT_SUBSCRIPT
METRICS_SUBSCRIPTThe rename procedure only tries to update the column DBGROUP or DBGROUPNAME. Only remove option will delete servers.On the other hand, it will remove saved encrypted DB credential from a java derby db with the old db group name, and reinsert back with new dbgroup name.If you can afford another test, can you check the log and paste the log (under directory log)?—
