### ISSUE TITLE
Allow specific group for new user

### ISSUE THREAD

**Issue by devalias** [yahoo/mysql_perf_analyzer#15]
Hi, please allow the ability to assign a label to a new user,  I don't want a user to be able to see other labels.

**Comment by xrao** [comment]
Can you explain in detail?

**Comment by devalias** [comment]
I would like to create a new user that can only view certain servers under a group, for instance allow only user "A" to only see group "A"  I probably should have said group instead of label.  :)

**Comment by xrao** [comment]
I am considering to add a restricted user type for this purpose. Will update you when I am done.

**Comment by xrao** [comment]
A user type "Restricted User" has been added to "User" screen. After a restricted user is created, you can use "DB Info" page, "Access Control" tab to assign/revoke user access.

**Comment by devalias** [comment]
Thanks, I will try this feature out soon.Sent with SolMail App--------- Original Message ---------
From: xrao 
To: yahoo/mysql_perf_analyzer 
Date: Thu Jul 09 17:27:39 EDT 2015
Subject: Re: [mysql_perf_analyzer] Allow specific group for new user (#15)

A user type "Restricted User" has been added to "User" screen. After a restricted user is created, you can use "DB Info" page, "Access Control" tab to assign/revoke user access.

**Comment by devalias** [comment]
hi, I created a new restricted user, dashboard looks fine but when I try to view realtime this pops up:
"No valid credential provided for DB ..."

**Comment by xrao** [comment]
Unfortunately, this is by design. We designed this tool so that every dev/dba/support can self register and use it for their own purpose, under the assumption every user will register their own database user/password for concerned databases. So, for now, you have to login as the restricted user, use DB Info page, credential tab, to add DB credentials to access the underlying DB. However, the access to the metrics data such as charts/alerts is not limited by this restriction. For the future, we can consider to copy DB credential to the restricted user when assign databases.

**Comment by devalias** [comment]
ok, thanks for the explanation.  yes, this feature will be nice since other users that are restricted would like to be able to view their servers realtime.

**Comment by xrao** [comment]
Updated. Please test.

**Comment by devalias** [comment]
Hi Xrao, updated and this works great.  Thanks!
